wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1777997658.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      3:
      - 13
      - 23
      - 61
      4: 3.10.4
      5: 0.16.6
      6: 4.34.1
      8:
      - 5
      13: linux-x86_64
trl_ppo_trainer_config:
  desc: null
  value:
    exp_name: pcmorlhf
    seed: 0
    log_with: wandb
    task_name: null
    model_name: PKU-Alignment/alpaca-7b-reproduced
    query_dataset: imdb
    reward_model: sentiment-analysis:lvwerra/distilbert-imdb
    remove_unused_columns: true
    tracker_kwargs/wandb/name: PKU-Alignment/PKU-SafeRLHF-10K/pcmorlhf/pc_alpha_h0.5_s0.5_pref0.5_0.5
    tracker_kwargs/wandb/entity: promotion-kim
    tracker_project_name: pcma
    steps: 20000
    learning_rate: 1.0e-05
    adap_kl_ctrl: true
    init_kl_coef: 0.2
    kl_penalty: kl
    target: 3.0
    horizon: 10000
    gamma: 1
    lam: 0.95
    cliprange: 0.2
    cliprange_value: 0.2
    vf_coef: 0.1
    batch_size: 4
    forward_batch_size: null
    mini_batch_size: 1
    gradient_accumulation_steps: 1
    world_size: 1
    ppo_epochs: 4
    max_grad_norm: 0.5
    optimize_cuda_cache: true
    optimize_device_cache: false
    early_stopping: true
    target_kl: 1
    compare_steps: 1
    ratio_threshold: 10.0
    use_score_scaling: false
    use_score_norm: false
    score_clip: null
    whiten_rewards: false
    is_encoder_decoder: false
    is_peft_model: true
    backward_batch_size: 1
    global_backward_batch_size: 1
    global_batch_size: 4
    total_ppo_epochs: 5000
